sonar.projectName=dtsse-agent-hub
sonar.projectKey=dtsse-agent-hub
sonar.language=typescript
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-integration/lcov.info
sonar.exclusions=src/instrumentation.ts,src/proxy.ts,test/**,src/store/generated/**
sonar.coverage.exclusions=src/app/**/*.tsx,src/cli/**
